### PR TITLE
Added a Slack External Command Example

### PR DESCRIPTION
**Pull request by rml596**
This pull requests add a Python script to be used as an external command to upload recordings to Slack. This includes a README file as to how to implement it.

### CODE REVIEW

**Comment by kdolan** [comment]
This looks fantastic! I have one concern with the [slack-token](https://github.com/kjdElectronics/fd-tone-notify/pull/19/commits/db1ad520347fd2b86aa91925bded5bc7959e9ec2#diff-f16108addd6357343e7294c83d5856ae68d28eb3eee24a494879e5d1cf49e393R26). 

I would prefer if this was moved to an environment variable / secrets.json. However, I can envision a use case for needing multiple slack tokens in a single configuration. Do you think it would be possible to change this to ```slack-token-env-var-name``` and then have the python script pull in the environment variable. Perhaps it might be more user accessible to put it into a secrets file in the same direction as slack-upload.py...

For security reasons I think is important for auth tokens or API keys to be kept out of the config file.

**Comment by rml596** [comment]
Yes, that's a good point. I don't think Python will be able to get FD-Tone-Notify variables though so it will need to be a system env variable.

**Comment by kdolan** [comment]
> Yes, that's a good point. I don't think Python will be able to get FD-Tone-Notify variables though so it will need to be a system env variable. So long as you're alright with that, I'll go back and edit the script.

Yeah, its not going to pull anything in but you could always make your own ```slack-secrets.json``` or .yaml or whatever and just have users add what they needed in there.

**Comment by rml596** [comment]
It been updated with a `slack-secrets.json` file. README has also been updated.

**Review by kdolan — APPROVED** [review]

**Pull request merged**
